// <auto-generated />
using System;
using ERPNext_PowerPlay;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERPNext_PowerPlay.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250424124228_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ERPNext_PowerPlay.Models.Cred", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("APIKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pass")
                        .HasColumnType("TEXT");

                    b.Property<string>("Secret")
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Creds");
                });

            modelBuilder.Entity("ERPNext_PowerPlay.Models.Frappe_DocList+data", b =>
                {
                    b.Property<int>("Job")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Grand_Total")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("JobDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("custom_print_count")
                        .HasColumnType("INTEGER");

                    b.HasKey("Job");

                    b.HasIndex("DocType", "Name", "Date");

                    b.ToTable("JobHistory");
                });

            modelBuilder.Entity("ERPNext_PowerPlay.Models.PrinterSetting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Compact")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Copies")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CopyName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("date('now')");

                    b.Property<DateTime?>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("date('now')");

                    b.Property<int>("DocType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FieldList")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilterList")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FontSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FrappeTemplateName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LetterHead")
                        .HasColumnType("TEXT");

                    b.Property<int>("Orientation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PageRange")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrintEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Printer")
                        .HasColumnType("TEXT");

                    b.Property<string>("REPX_Template")
                        .HasColumnType("TEXT");

                    b.Property<int>("Scaling")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UOM")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserFilter")
                        .HasColumnType("TEXT");

                    b.Property<string>("WarehouseFilter")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("PrinterSetting");
                });

            modelBuilder.Entity("ERPNext_PowerPlay.Models.ReportList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndPoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldList")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilterList")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("ReportList");
                });

            modelBuilder.Entity("ERPNext_PowerPlay.Models.Settings", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("ERPNext_PowerPlay.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("selected")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ERPNext_PowerPlay.Models.Warehouse", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("selected")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Warehouse");
                });
#pragma warning restore 612, 618
        }
    }
}
